bounds:
  dend.g_pas slope: !!python/tuple
  - 1.0E-10
  - 1.0E-5
  dend.g_pas tau: !!python/tuple
  - 25.
  - 400.
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-7
  ais.gbar_nax: !!python/tuple
  - 0.02
  - 0.5
  ais.gkmbar: !!python/tuple
  - 0.0005
  - 0.015
  ais.sha_nax: !!python/tuple
  - -5.0
  - -1.0
  axon.gbar_nax: !!python/tuple
  - 0.02
  - 0.1
  axon.gkabar: !!python/tuple
  - 0.01
  - 0.18
  dend.gbar_nas: !!python/tuple
  - 0.01
  - 0.05
  dend.gbar_nas bo: !!python/tuple
  - 3
  - 6
  dend.gbar_nas min: !!python/tuple
  - 0.0
  - 0.015
  dend.gbar_nas slope: !!python/tuple
  - -0.0004
  - 0.0
  dend.gkabar: !!python/tuple
  - 0.01
  - 0.25
  soma.gCa factor: !!python/tuple
  - 0.01
  - 2.0
  soma.gCadepK factor: !!python/tuple
  - 0.01
  - 2.0
  soma.gbar_nas: !!python/tuple
  - 0.01
  - 0.05
  soma.gkabar: !!python/tuple
  - 0.01
  - 0.05
  soma.gkdrbar: !!python/tuple
  - 0.01
  - 0.06
  soma.gkmbar: !!python/tuple
  - 0.0005
  - 0.005
  soma.sh_nas/x: !!python/tuple
  - 0.1
  - 6.0
default_params:
  dend.gbar_nas bo: 5
feature_names:
- dend R_inp
- distal_dend R_inp
- soma R_inp
- v_th
- ADP
- AHP
- spont_firing
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- dend_amp
- rheobase
- soma_peak
- adi
- f_I_slope
- f_I_residuals
update_context:
- - optimize_DG_GC_hoc_leak
  - reset_mechanisms
- - optimize_DG_GC_hoc_leak
  - update_mechanisms_leak
- - optimize_DG_GC_hoc_spiking
  - update_mechanisms_spiking
get_features_stages:
- source: optimize_DG_GC_hoc_leak
  compute_features: compute_features_leak
  get_args_static: get_args_static_leak
- source: optimize_DG_GC_hoc_spiking
  compute_features: compute_features_spike_shape
- source: optimize_DG_GC_hoc_spiking
  get_args_dynamic: get_args_dynamic_fI
  compute_features: compute_features_fI
  filter_features: filter_features_fI
get_objectives:
  optimize_DG_GC_hoc_leak: get_objectives_leak
  optimize_DG_GC_hoc_spiking: get_objectives_spiking
kwargs:
  mech_file_path: mechanisms/20180209_DG_GC_hoc_leak_mech.yaml
  gid: 0
  population: GC
  spines: False
  cvode: False
  verbose: 1
  daspk: True
  config_file: ../dentate/config/Small_Scale_Control_log_normal_weights.yaml
  template_paths: ../dgc/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  # dataset_prefix: /mnt/s
  dataset_prefix: ../dentate/datasets
  results_path: data
objective_names:
- dend R_inp
- distal_dend R_inp
- soma R_inp
- v_th
- ADP
- AHP
- spont_firing
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- dend_amp
- soma_peak
- th_count
- adi
- f_I_slope
optimization_title: DG_GC_hoc_leak_spiking
param_gen: PopulationAnnealing
param_names:
- dend.g_pas slope
- dend.g_pas tau
- soma.g_pas
- soma.gbar_nas
- dend.gbar_nas
- dend.gbar_nas bo
- dend.gbar_nas min
- dend.gbar_nas slope
- axon.gbar_nax
- ais.gbar_nax
- soma.gkabar
- dend.gkabar
- soma.gkdrbar
- axon.gkabar
- soma.sh_nas/x
- ais.sha_nax
- soma.gCa factor
- soma.gCadepK factor
- soma.gkmbar
- ais.gkmbar
rel_bounds:
- - dend.gbar_nas min
  - '<'
  - 1.0
  - soma.gbar_nas
- - dend.gbar_nas
  - '<='
  - 1.0
  - soma.gbar_nas
- - dend.gbar_nas
  - '>'
  - 1.0
  - dend.gbar_nas min
- - axon.gbar_nax
  - '>'
  - 1.0
  - soma.gbar_nas
- - ais.gbar_nax
  - '>'
  - 2.0
  - axon.gbar_nax
#- - dend.gkabar
#  - '>'
#  - 1.0
#  - soma.gkabar
- - axon.gkabar
  - <
  - 3.0
  - soma.gkabar
target_range:
  dend R_inp: 1.
  soma R_inp: 0.5
  ADP: 0.01
  AHP: 0.005
  ais_delay: 0.0005
  dend_amp: 0.0002
  rebound_firing: 0.002
  slow_depo: 0.1
  soma_peak: 2.0
  spont_firing: 0.002
  th_count: 0.002
  v_th: 0.01
  vm_stability: 0.1
  f_I_slope: 0.5
target_val:
  dend R_inp: 375.
  soma R_inp: 295.
  ADP: 0.0
  AHP: 4.0
  ais_delay: 0.0
  dend_amp: 0.3
  rebound_firing: 0
  slow_depo: 10.0
  soma_peak: 40.0
  spont_firing: 0
  th_count: 1
  v_th: -48.0
  vm_stability: 0.0
  f_I_slope: 53.0
x0:
  dend.g_pas slope: 1.058E-08
  dend.g_pas tau: 3.886E+01
  soma.g_pas: 1.050E-10
  ais.gbar_nax: 0.1681
  ais.gkmbar: 0.01286
  ais.sha_nax: -2.659
  axon.gbar_nax: 0.06
  axon.gkabar: 0.05266
  dend.gbar_nas: 0.03
  dend.gbar_nas bo: 4
  dend.gbar_nas min: 0.0
  dend.gbar_nas slope: -0.0001
  dend.gkabar: 0.04
  soma.gCa factor: 0.3364
  soma.gCadepK factor: 2.
  soma.gbar_nas: 0.03
  soma.gkabar: 0.02108
  soma.gkdrbar: 0.04299
  soma.gkmbar: 0.004286
  soma.sh_nas/x: 1.219