bounds:
  dend.g_pas slope: !!python/tuple
  - 1.0E-9
  - 1.0E-2
  dend.g_pas tau: !!python/tuple
  - 25.
  - 400.
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-4
  e_pas: !!python/tuple
  - -75.0
  - -60.0
  soma.ghbar: !!python/tuple
  - 1.0E-9
  - 1.0E-2
  dend.ghbar: !!python/tuple
    - 1.0E-9
    - 1.0E-2
feature_names:
- dend R_inp
- term_dend R_inp
- soma R_inp
- soma R_inp (no h)
- soma vm_rest
- soma vm_rest (no h)
update_context:
- - optimize_DG_MC_leak
  - reset_biophysics
- - optimize_DG_MC_leak
  - update_mechanisms_leak
get_features_stages:
- source: optimize_DG_MC_leak
  get_args_static: get_args_static_leak
  compute_features: compute_features_leak
get_objectives:
  optimize_DG_MC_leak: get_objectives_leak
kwargs:
  mech_file_path: mechanisms/20181127_DG_MC_only_leak_mech.yaml  # 20180905_DG_MC_excitability_mech.yaml
  gid: 1000000
  cell_type: MC
  correct_for_spines: False
  verbose: 2
  daspk: True
  cvode: False
  config_file: Small_Scale_Control_MC_BC.yaml
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
objective_names:
# - dend R_inp
- term_dend R_inp
- soma R_inp
- soma R_inp (no h)
- soma vm_rest
- soma vm_rest (no h)
optimization_title: DG_MC_leak
param_gen: PopulationAnnealing
param_names:
- soma.g_pas
- dend.g_pas slope
- dend.g_pas tau
- e_pas
- soma.ghbar
- dend.ghbar
target_range:
  dend R_inp: 1.
  soma R_inp: 0.5
  soma vm_rest: 0.1
target_val:
  term_dend R_inp: 1000.
  dend R_inp: 117.
  soma R_inp: 126.
  soma R_inp (no h): 144.
  soma vm_rest: -66.0
  soma vm_rest (no h): -70.0
x0:
  dend.g_pas slope: 1.058E-5
  dend.g_pas tau: 3.886E+2
  soma.g_pas: 1.050E-5
  e_pas: -66.0
  soma.ghbar: 1.e-5
  dend.ghbar: 1.e-5
