bounds:
  soma.C: !!python/tuple
  - 0.1 
  - 2.0
  soma.k: !!python/tuple
  - 0.2 
  - 1.6
  soma.v_peak: !!python/tuple
  - 0.0
  - 50.0
  soma.a: !!python/tuple
  - 0.01 
  - 0.2
  soma.b: !!python/tuple
  - -2.0
  - 15.0
  soma.c: !!python/tuple
  - -70.0
  - -40.0
  soma.d: !!python/tuple
  - -60.0
  - 150.0
default_params:
rel_bounds:
feature_names:
- soma R_inp
- soma vm_rest
update_context:
- - optimize_DG_BC_Izhi_leak
  - update_mechanisms_leak
get_features_stages:
- source: optimize_DG_BC_Izhi_leak
  get_args_static: get_args_static_leak
  compute_features: compute_features_leak
get_objectives:
  optimize_DG_BC_Izhi_leak: get_objectives_leak
kwargs:
  mech_file_path: mechanisms/20200611_DG_MC_only_Izhi_leak_mech.yaml 
  gid: 1039000
  cell_type: BC
  correct_for_spines: False
  verbose: 2
  daspk: True  # False
  cvode: False
  config_file: Small_Scale_Control_MC_BC_NewMorph.yaml 
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
  vr: -62.
  vt: -40.
  celltype: 5
objective_names:
- soma R_inp
optimization_title: DG_BC_Izhi_leak
param_gen: PopulationAnnealing
param_names:
- soma.C
- soma.k
- soma.a
- soma.b
- soma.c
- soma.d
- soma.v_peak
target_range:
  soma R_inp: 0.5
target_val:
  soma R_inp: 222.
x0:
  soma.C: 0.5
  soma.k: 1.6
  soma.a: 0.03
  soma.b: -2.0
  soma.c: -65.0
  soma.d: 100
  soma.v_peak: 35.
